spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mystore
    username: postgres
    password: Viking07
  flyway:
    baseline-on-migrate: true